### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by securespider** [thewebscraping/django-chunk-file-upload#7]
Error message:
'admin_tags' is not a registered tag library. Must be one of: admin_list admin_modify admin_urls cache i18n l10n log rest_framework static tz

In template /django_chunk_file_upload/templates/django_chunk_file_upload/forms/widgets/drag_drop_input.html, error at line 1

Remedy:
Remove admin tags from that line and everything works

**Comment by thewebscraping** [comment]
@securespider 
Thanks for support, it has been fixed
